import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { cookies } from 'next/headers';
import { Suspense } from 'react';
import { redirect } from 'next/navigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-100 p-4 flex gap-4">
          <Link href="/">Home</Link>
          <Link href="/issue">Issue</Link>

          <div className="ml-auto">
            <Suspense>
              {cookies().then((c) => (
                <>
                  {c.get('name')?.value ? (
                    <div className="flex gap-2">
                      <p>Hi {c.get('name')?.value}!</p>
                      <form action={signOut}>
                        <button className="hover:underline text-gray-500">
                          Sign out
                        </button>
                      </form>
                    </div>
                  ) : (
                    <form action={signIn} className="flex gap-2">
                      <input
                        className="border px-2"
                        type="text"
                        name="name"
                        placeholder="Enter your name..."
                      />
                      <button>Sign in</button>
                    </form>
                  )}
                </>
              ))}
            </Suspense>
          </div>
        </nav>

        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}

async function signIn(formData: FormData) {
  'use server';
  const name = formData.get('name');
  if (typeof name !== 'string') return;

  const jar = await cookies();
  jar.set('name', name);
}

async function signOut() {
  'use server';
  const jar = await cookies();

  jar.delete('name');
  redirect('/');
}
